Novel-Nest/Models/BookInfoViewModel.cs
using Models;

namespace Novel_Nest.Models
{
    public class BookInfoViewModel
    {
            public int Id { get; set; }
            public string Title { get; set; }
            public string Author { get; set; }
            public int CategoryId { get; set; }
            public string CategoryName { get; set; }
            public DateTime? DateStarted { get; set; }
            public DateTime? DateFinished { get; set; }
            public int? Rating { get; set; }
            public string Review { get; set; }
            public bool Finished { get; set; }
            public string CoverImageUrl { get; set; }

            public BookInfoViewModel(BookModel book)
            {
                Id = book.Id;
                Title = book.Title;
                Author = book.Author;
                CategoryId = book.CategoryId;
                CategoryName = book.CategoryName;
                DateStarted = book.DateStarted;
                DateFinished = book.DateFinished;
                Rating = book.Rating;
                Review = book.Review;
                Finished = book.Finished;
                CoverImageUrl = book.CoverImageUrl; 
            }

    }
}

Novel-Nest/Controllers/BookController.cs
using Interfaces;
using Microsoft.AspNetCore.Mvc;
using Models;
using Novel_Nest.Models;
using Novel_Nest_Core;
using System.Threading.Tasks;

namespace Novel_Nest.Controllers
{
    public class BookController : Controller
    {
        private readonly BookService _bookService;
        private readonly APIService _apiService;
        private readonly CategoryService _categoryService;

        public BookController(BookService bookService, APIService apiService, CategoryService categoryService)
        {
            _bookService = bookService;
            _apiService = apiService;
            _categoryService = categoryService;
        }
        [HttpGet]
        public async Task<IActionResult> NewBook()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToAction("LoginPage", "Home");
            }

            var categories = await _categoryService.GetUserAndDefaultCategoriesAsync(userId.Value);

            var model = new CategoryViewModel
            {
                Categories = categories
            };
            return View(model);
        }

        [HttpPost]
		public async Task<IActionResult> AddBook(BookModel book)
		{
			if (ModelState.IsValid)
			{
				var userId = HttpContext.Session.GetInt32("UserId");
				if (userId == null)
				{
					return RedirectToAction("LoginPage", "Home");
				}
				book.UserId = userId.Value;
				bool success = await _bookService.AddBookAsync(book);
				if (success)
				{
					TempData["Message"] = "Book successfully added.";
					return RedirectToAction("NewBook");
				}
				else
				{
					TempData["ErrorMessage"] = "Failed to create book. Please try again.";
					return RedirectToAction("NewBook");
				}
			}
			else
			{
				TempData["ErrorMessage"] = "Invalid book data. Please try again.";
				return RedirectToAction("NewBook");
			}
		}

		[HttpGet]
		public async Task<IActionResult> EditBook()
		{
			var userId = HttpContext.Session.GetInt32("UserId");
			if (userId == null)
			{
				return RedirectToAction("LoginPage", "Home");
			}

			var categories = await _categoryService.GetUserAndDefaultCategoriesAsync(userId.Value);
			var books = _bookService.GetBooks(userId.Value); 

			var model = new EditBookViewModel
			{
				Categories = categories,
				Books = books
			};
       
            return View(model);
		}

		[HttpPost]
        public async Task<IActionResult> DeleteBook(int Id)
        {
            try
            {
                bool isInNightstand = await _bookService.IsBookInNightstandAsync(Id);
                if (isInNightstand)
                {
                    TempData["Message"] = "CannotDeleteInNightstand"; // Specifieke sleutel voor deze situatie
                    return RedirectToAction("EditBook");
                }
                await _bookService.DeleteBookAsync(Id);
                TempData["Message"] = "Deleted";
                return RedirectToAction("EditBook");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Failed to delete: " + ex.Message;
                return View("ErrorView");
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditLibraryBook(BookModel book)
        {
            try
            {
                var userId = HttpContext.Session.GetInt32("UserId");
                if (userId == null)
                {
                    return RedirectToAction("LoginPage", "Home");
                }
                book.UserId = userId.Value; 
                bool success = await _bookService.EditLibraryBookAsync(book);
                if (success)
                {
                    TempData["Message"] = "Edited";
                    return RedirectToAction("EditBook");
                }
                else
                {
                    TempData["ErrorMessage"] = "Failed to edit. You may not have permission to edit this book.";
                    return RedirectToAction("EditBook");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Failed to edit: " + ex.Message;
                return View("ErrorView");
            }
        }

        //[HttpGet]
        //public async Task<IActionResult> SearchBooks(string query)
        //{
        //    if (string.IsNullOrWhiteSpace(query))
        //    {
        //        return Json(new { success = false, message = "Query cannot be empty." });
        //    }

        //    var searchResult = await _apiService.SearchBooksAsync(query);
        //    if (searchResult == null || searchResult.Docs == null || !searchResult.Docs.Any())
        //    {
        //        return Json(new { success = false, message = "No books found." });
        //    }

        //    return Json(new { success = true, books = searchResult.Docs });
        //}


        //[HttpPost]
        //public async Task<IActionResult> AddBookFromSearch(string olid)
        //{
        //    var userId = HttpContext.Session.GetInt32("UserId");
        //    if (userId == null)
        //    {
        //        return Json(new { success = false, message = "User not logged in." });
        //    }

        //    var book = await _apiService.SearchBooksAsync(olid);
        //    if (book == null || book.Docs == null || !book.Docs.Any())
        //    {
        //        return Json(new { success = false, message = "Book not found." });
        //    }

        //    var firstBook = book.Docs.First();
        //    var addSuccess = await _bookService.AddBookFromSearchAsync(firstBook, userId.Value);
        //    if (addSuccess)
        //    {
        //        return Json(new { success = true, message = "Book added successfully." });
        //    }
        //    else
        //    {
        //        return Json(new { success = false, message = "Failed to add the book." });
        //    }
        //}

    }
}

Novel-Nest/Controllers/BookshelfController.cs
using Microsoft.AspNetCore.Mvc;
using Models;
using Novel_Nest_Core;
using Novel_Nest.Models;

namespace Novel_Nest.Controllers
{
    public class BookshelfController : Controller
    {
        private readonly BookService _bookService;
        private readonly UserService _userService;

        public BookshelfController(BookService bookService, UserService userService)
        {
            _bookService = bookService;
            _userService = userService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToAction("LoginPage", "Home");
            }
            var books = _bookService.GetBooks(userId.Value);
            var userName = await _userService.GetUserNameAsync(userId.Value);

            var model = new BooksViewModel
            {
                Books = books,
                UserName = userName 
            };
            return View(model);
        }

        public IActionResult AddBooks()
        {
            return View();
        }

        public IActionResult EditBook()
        {
            return View();
        }

        public async Task<IActionResult> BookInfo(int bookId)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToAction("LoginPage", "Home");
            }

            var book = await _bookService.GetBookByUserIdAndBookId(userId.Value, bookId);

            if (book == null)
            {
                return NotFound();
            }

            var model = new BookInfoViewModel(book);

            return View(model);
        }
    }
}

Novel-Nest/Views/Bookshelf/BookInfo.cshtml
@using Models
@model BookInfoViewModel
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <link rel="stylesheet" type="text/css" href="~/css/BookInfo.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Novel Nest</title>
</head>
<body>
    <div class="info-container">
        <h1>@Model.Title</h1>
        <p>Author: @Model.Author</p>
        <p>Category: @Model.CategoryName</p>
        <p>Rating: @(Model.Rating.HasValue ? Model.Rating.ToString() : "Add a book to your nightstand to give it a rating!")</p>
        <p>Review: @(String.IsNullOrEmpty(Model.Review) ? "Add a book to your nightstand to give it a review!" : Model.Review)</p>
        <p>Started at: @(Model.DateStarted == null ? "Add a book to your nightstand to give it a starting date!" : Model.DateStarted.Value.ToString("d"))</p>
        <p>Finished at: @(Model.DateFinished == null ? "Add a book to your nightstand to give it a finishing date!" : Model.DateFinished.Value.ToString("d"))</p>
        <p>Book is @(Model.Finished ? "finished" : "not finished")</p>
    </div>
</body>
</html>

Novel-Nest/Views/Bookshelf/Index.cshtml
@using Models
@model BooksViewModel
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <link rel="stylesheet" type="text/css" href="~/css/BookshelfIndex.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Novel Nest</title>
</head>
<body>
    <h1>Hi @Model.UserName, welcome to your library!</h1>
    <p>Add new books, add categories</p>
    <input class="btn" type="button" value="Create new category" onclick="location.href='@Url.Action("Category", "Category")'" />
    <input class="btn" type="button" value="Add new book" onclick="location.href='@Url.Action("NewBook", "Book")'" />
    <input class="btn" type="button" value="Edit books" onclick="location.href='@Url.Action("EditBook", "Book")'" />
    <div class="Searchbar">
        <input type="text" class="search-bar" id="searchInput" placeholder="Search book">
    </div>
    <div class="book-list">
        @foreach (var book in Model.Books)
        {
            <div class="books">
                <div class="book-title">@book.Title <br /> @book.Author</div>  @book.CategoryName
                <br />
                <button type="button" class="info-button" onclick="location.href='@Url.Action("BookInfo", "Bookshelf", new { bookId = book.Id })'">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
                    </svg>
                </button>
            </div>
        }
    </div>
    <script>
        const searchInput = document.getElementById('searchInput');
        const books = document.querySelectorAll('.books');

        searchInput.addEventListener('input', function () {
            const searchTerm = searchInput.value.trim().toLowerCase(); // Haal de zoekterm op en converteer naar lowercase

            books.forEach(function (book) {
                if (book.innerText.toLowerCase().includes(searchTerm)) {
                    book.style.display = 'block';
                } else {
                    book.style.display = 'none';
                }
            });
        });
    </script>
</body>
</html>